"use client";

import { useMemo, useState } from "react";
import {
  ArrowUpRight, BadgeCheck, BarChart3, Building2, CalendarDays,
  ChevronRight, CircleDollarSign, ClipboardCheck, FileBadge, FileSignature, HelpCircle,
  Package, Pill, Plus, ReceiptText, Search, Send, Settings,
  SlidersHorizontal, Sparkles, TrendingUp, Users, WalletCards, X
} from "lucide-react";

type ModuleKey = "financeiro" | "estoque" | "relatorios" | "fiscal" | "minha-clinica" | "configuracoes" | "ajuda" | "receituarios" | "creditos" | "termos" | "atestados" | "sms" | "lembretes" | "cadastros";
type Config = { eyebrow: string; title: string; description: string; action: string; icon: React.ElementType; stats: { label: string; value: string; hint: string }[]; tabs: string[]; rows: { title: string; detail: string; meta: string; status: string }[] };

const configs: Record<ModuleKey, Config> = {
  financeiro: { eyebrow: "Gestão financeira", title: "Financeiro", description: "Acompanhe recebimentos, despesas e o fluxo de caixa da clínica.", action: "Novo lançamento", icon: WalletCards, stats: [{ label: "Receitas no mês", value: "R$ 48.320", hint: "+12% no período" }, { label: "A receber", value: "R$ 14.850", hint: "18 lançamentos" }, { label: "Despesas", value: "R$ 21.460", hint: "44% da receita" }, { label: "Saldo projetado", value: "R$ 26.860", hint: "Até o fim do mês" }], tabs: ["Visão geral", "Contas a receber", "Contas a pagar"], rows: [{ title: "Consulta dermatológica", detail: "Mariana Costa · PIX", meta: "Hoje, 14:30 · R$ 380,00", status: "Pago" }, { title: "Fornecedor de materiais", detail: "MedSupply Brasil", meta: "Vence amanhã · R$ 1.240,00", status: "Pendente" }, { title: "Procedimento estético", detail: "Carla Mendes · Cartão 3x", meta: "22 jul · R$ 1.850,00", status: "Agendado" }] },
  estoque: { eyebrow: "Suprimentos", title: "Estoque", description: "Controle produtos, insumos, lotes e validade sem surpresas.", action: "Cadastrar item", icon: Package, stats: [{ label: "Itens ativos", value: "284", hint: "12 categorias" }, { label: "Estoque baixo", value: "9", hint: "Requer atenção" }, { label: "Próximos do vencimento", value: "6", hint: "Nos próximos 30 dias" }, { label: "Valor em estoque", value: "R$ 36.940", hint: "Custo estimado" }], tabs: ["Todos os itens", "Estoque baixo", "Lotes e validade"], rows: [{ title: "Luva nitrílica M", detail: "Descartáveis · Lote 2406B", meta: "18 caixas disponíveis", status: "Baixo" }, { title: "Ácido hialurônico 1ml", detail: "Injetáveis · Lote AH992", meta: "42 unidades · vence dez/2027", status: "Disponível" }, { title: "Soro fisiológico 500ml", detail: "Uso clínico · Lote SF183", meta: "86 unidades", status: "Disponível" }] },
  relatorios: { eyebrow: "Inteligência da clínica", title: "Relatórios", description: "Transforme a operação em decisões com indicadores claros.", action: "Gerar relatório", icon: BarChart3, stats: [{ label: "Atendimentos", value: "438", hint: "+8% no mês" }, { label: "Ticket médio", value: "R$ 612", hint: "+4,2%" }, { label: "Taxa de retorno", value: "68%", hint: "Meta: 72%" }, { label: "Ocupação da agenda", value: "84%", hint: "Melhor em 6 meses" }], tabs: ["Executivo", "Atendimentos", "Comercial"], rows: [{ title: "Desempenho mensal", detail: "Receita, conversão e ocupação", meta: "Atualizado hoje", status: "Pronto" }, { title: "Produção por profissional", detail: "Comparativo de atendimentos", meta: "Últimos 30 dias", status: "Pronto" }, { title: "Origem de novos pacientes", detail: "Canais e campanhas", meta: "Julho de 2026", status: "Processando" }] },
  fiscal: { eyebrow: "Documentos fiscais", title: "Fiscal", description: "Emita, acompanhe e organize os documentos fiscais da operação.", action: "Emitir nota", icon: ReceiptText, stats: [{ label: "Notas emitidas", value: "126", hint: "Neste mês" }, { label: "Valor faturado", value: "R$ 72.410", hint: "Competência atual" }, { label: "Pendentes", value: "4", hint: "Aguardando emissão" }, { label: "Canceladas", value: "2", hint: "1,5% do total" }], tabs: ["Notas fiscais", "Pendências", "Configuração"], rows: [{ title: "NFS-e #202600184", detail: "Mariana Costa", meta: "R$ 380,00 · 21 jul", status: "Autorizada" }, { title: "NFS-e #202600183", detail: "João Martins", meta: "R$ 720,00 · 21 jul", status: "Autorizada" }, { title: "Atendimento #AG-1092", detail: "Carla Mendes", meta: "R$ 1.850,00", status: "Pendente" }] },
  "minha-clinica": { eyebrow: "Administração", title: "Minha clínica", description: "Centralize dados, unidades, profissionais e horários de funcionamento.", action: "Adicionar unidade", icon: Building2, stats: [{ label: "Unidades", value: "2", hint: "Ambas ativas" }, { label: "Profissionais", value: "12", hint: "9 em atendimento" }, { label: "Salas", value: "8", hint: "6 disponíveis hoje" }, { label: "Serviços", value: "34", hint: "30 ativos" }], tabs: ["Unidades", "Profissionais", "Serviços"], rows: [{ title: "Unidade Centro", detail: "Rua das Flores, 240 · São Paulo", meta: "Seg–Sex, 08h às 20h", status: "Ativa" }, { title: "Unidade Jardins", detail: "Alameda Santos, 1150 · São Paulo", meta: "Seg–Sáb, 08h às 18h", status: "Ativa" }, { title: "Sala de procedimentos 03", detail: "Unidade Centro · 2º andar", meta: "Manutenção em 29 jul", status: "Atenção" }] },
  configuracoes: { eyebrow: "Preferências", title: "Configurações", description: "Personalize regras, notificações, integrações e acessos.", action: "Salvar alterações", icon: Settings, stats: [{ label: "Integrações ativas", value: "3", hint: "E-mail, WhatsApp e fiscal" }, { label: "Perfis de acesso", value: "4", hint: "12 usuários" }, { label: "Automações", value: "7", hint: "6 ativas" }, { label: "Último backup", value: "Hoje", hint: "Às 03:15" }], tabs: ["Geral", "Notificações", "Segurança"], rows: [{ title: "Lembretes automáticos", detail: "WhatsApp 24h antes da consulta", meta: "Todos os pacientes", status: "Ativo" }, { title: "Autenticação em duas etapas", detail: "Proteção adicional para administradores", meta: "2 de 3 administradores", status: "Atenção" }, { title: "Integração de e-mail", detail: "siteclinicaweb@gmail.com", meta: "Sincronizado há 8 min", status: "Ativo" }] },
  ajuda: { eyebrow: "Suporte", title: "Central de ajuda", description: "Encontre respostas rápidas ou fale com nossa equipe.", action: "Abrir chamado", icon: HelpCircle, stats: [{ label: "Artigos disponíveis", value: "48", hint: "Organizados por módulo" }, { label: "Chamados abertos", value: "1", hint: "Resposta em até 2h" }, { label: "Status da plataforma", value: "Online", hint: "Todos os serviços" }, { label: "Novidades", value: "6", hint: "Na versão atual" }], tabs: ["Mais acessados", "Meus chamados", "Novidades"], rows: [{ title: "Como cadastrar um novo paciente?", detail: "Clientes · 3 minutos de leitura", meta: "Atualizado em 15 jul", status: "Artigo" }, { title: "Configurando lembretes por WhatsApp", detail: "Comunicação · Guia passo a passo", meta: "Atualizado em 10 jul", status: "Artigo" }, { title: "Erro ao emitir uma nota fiscal", detail: "Fiscal · Soluções mais comuns", meta: "Atualizado em 02 jul", status: "Artigo" }] },
  receituarios: { eyebrow: "Atendimento", title: "Receituários", description: "Crie prescrições padronizadas e mantenha o histórico do paciente.", action: "Nova receita", icon: Pill, stats: [{ label: "Emitidos no mês", value: "86", hint: "+9% no período" }, { label: "Modelos salvos", value: "12", hint: "Da equipe" }, { label: "Assinados", value: "82", hint: "95% do total" }, { label: "Rascunhos", value: "4", hint: "Aguardando revisão" }], tabs: ["Recentes", "Modelos", "Rascunhos"], rows: [{ title: "Mariana Costa", detail: "Dra. Ana Ferreira · Dermatologia", meta: "Hoje, 10:42", status: "Assinado" }, { title: "Roberto Lima", detail: "Dr. Paulo Mendes · Clínica geral", meta: "Ontem, 16:18", status: "Assinado" }, { title: "Fernanda Alves", detail: "Dra. Ana Ferreira · Dermatologia", meta: "Salvo há 25 min", status: "Rascunho" }] },
  creditos: { eyebrow: "Atendimento", title: "Créditos de pacotes", description: "Acompanhe sessões contratadas, utilizadas e disponíveis.", action: "Novo pacote", icon: BadgeCheck, stats: [{ label: "Pacotes ativos", value: "74", hint: "52 pacientes" }, { label: "Créditos disponíveis", value: "318", hint: "Todas as categorias" }, { label: "A vencer", value: "21", hint: "Nos próximos 30 dias" }, { label: "Utilizados no mês", value: "96", hint: "+14%" }], tabs: ["Pacotes ativos", "A vencer", "Histórico"], rows: [{ title: "Mariana Costa", detail: "Laser facial · 6 sessões", meta: "4 créditos disponíveis", status: "Ativo" }, { title: "Carla Mendes", detail: "Drenagem · 10 sessões", meta: "2 créditos · vence 30 jul", status: "Atenção" }, { title: "João Martins", detail: "Fisioterapia · 12 sessões", meta: "8 créditos disponíveis", status: "Ativo" }] },
  termos: { eyebrow: "Atendimento", title: "Termos de consentimento", description: "Organize modelos, assinaturas e documentos vinculados ao atendimento.", action: "Novo termo", icon: FileSignature, stats: [{ label: "Assinados no mês", value: "112", hint: "98% digitalmente" }, { label: "Aguardando assinatura", value: "7", hint: "Enviar lembrete" }, { label: "Modelos ativos", value: "18", hint: "Revisados" }, { label: "Vencendo", value: "3", hint: "Requer renovação" }], tabs: ["Documentos", "Modelos", "Pendências"], rows: [{ title: "Consentimento para procedimento", detail: "Mariana Costa · Dra. Ana Ferreira", meta: "Assinado hoje às 09:20", status: "Assinado" }, { title: "Uso de imagem", detail: "Roberto Lima · Clínica Centro", meta: "Enviado há 2 horas", status: "Pendente" }, { title: "Termo LGPD", detail: "Fernanda Alves", meta: "Assinado em 18 jul", status: "Assinado" }] },
  atestados: { eyebrow: "Atendimento", title: "Atestados", description: "Emita documentos clínicos com rastreabilidade e assinatura.", action: "Novo atestado", icon: FileBadge, stats: [{ label: "Emitidos no mês", value: "32", hint: "Por 6 profissionais" }, { label: "Assinados", value: "31", hint: "97% do total" }, { label: "Modelos", value: "5", hint: "Padronizados" }, { label: "Cancelados", value: "1", hint: "Com justificativa" }], tabs: ["Recentes", "Modelos", "Cancelados"], rows: [{ title: "João Martins", detail: "Dr. Paulo Mendes · 1 dia", meta: "Emitido hoje às 11:30", status: "Assinado" }, { title: "Fernanda Alves", detail: "Dra. Ana Ferreira · Comparecimento", meta: "Emitido ontem", status: "Assinado" }, { title: "Rafael Souza", detail: "Dr. Paulo Mendes · 2 dias", meta: "Rascunho salvo", status: "Rascunho" }] },
  sms: { eyebrow: "Comunicação", title: "Envio de mensagens", description: "Comunique avisos, confirmações e campanhas aos pacientes.", action: "Nova mensagem", icon: Send, stats: [{ label: "Enviadas no mês", value: "1.248", hint: "SMS e WhatsApp" }, { label: "Entregues", value: "96,8%", hint: "Excelente" }, { label: "Respostas", value: "342", hint: "27,4% de retorno" }, { label: "Agendadas", value: "4", hint: "Próximos 7 dias" }], tabs: ["Conversas", "Campanhas", "Modelos"], rows: [{ title: "Confirmação de consulta", detail: "142 destinatários · WhatsApp", meta: "Enviada hoje às 08:00", status: "Concluída" }, { title: "Campanha de retorno", detail: "86 destinatários · SMS", meta: "Agendada para amanhã", status: "Agendada" }, { title: "Lembrete pós-procedimento", detail: "Automação · WhatsApp", meta: "32 mensagens hoje", status: "Ativo" }] },
  lembretes: { eyebrow: "Comunicação", title: "Lembretes", description: "Automatize confirmações e reduza faltas na agenda.", action: "Novo lembrete", icon: CalendarDays, stats: [{ label: "Automações ativas", value: "7", hint: "WhatsApp e e-mail" }, { label: "Confirmações hoje", value: "38", hint: "82% da agenda" }, { label: "Aguardando resposta", value: "6", hint: "Até 18h" }, { label: "Faltas evitadas", value: "14", hint: "Estimativa mensal" }], tabs: ["Automações", "Hoje", "Histórico"], rows: [{ title: "24h antes da consulta", detail: "WhatsApp · Todos os serviços", meta: "46 envios previstos hoje", status: "Ativo" }, { title: "2h antes do procedimento", detail: "SMS · Procedimentos estéticos", meta: "12 envios previstos hoje", status: "Ativo" }, { title: "Pesquisa pós-atendimento", detail: "E-mail · 2h após a consulta", meta: "Pausado pela equipe", status: "Pausado" }] },
  cadastros: { eyebrow: "Base da clínica", title: "Cadastros", description: "Gerencie dados auxiliares usados em toda a operação.", action: "Novo cadastro", icon: Users, stats: [{ label: "Profissionais", value: "12", hint: "9 ativos hoje" }, { label: "Serviços", value: "34", hint: "6 categorias" }, { label: "Convênios", value: "8", hint: "Todos ativos" }, { label: "Formas de pagamento", value: "11", hint: "3 integrações" }], tabs: ["Profissionais", "Serviços", "Convênios"], rows: [{ title: "Dra. Ana Ferreira", detail: "Dermatologia · CRM 123456", meta: "Unidade Centro e Jardins", status: "Ativo" }, { title: "Consulta dermatológica", detail: "Serviço · 50 minutos", meta: "R$ 380,00", status: "Ativo" }, { title: "Plano Saúde Mais", detail: "Convênio · tabela 2026", meta: "Atualizado em 01 jul", status: "Ativo" }] },
};

const statusColor = (s: string) => s === "Ativo" || s === "Pago" || s === "Assinado" || s === "Autorizada" || s === "Disponível" || s === "Pronto" || s === "Concluída" ? "bg-emerald-50 text-emerald-700" : s === "Atenção" || s === "Baixo" || s === "Pendente" || s === "Rascunho" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600";

export default function ModulePrototype({ module }: { module: ModuleKey }) {
  const c = configs[module];
  const Icon = c.icon;
  const [tab, setTab] = useState(c.tabs[0]);
  const [search, setSearch] = useState("");
  const [modal, setModal] = useState(false);
  const rows = useMemo(() => c.rows.filter(r => (r.title + r.detail).toLowerCase().includes(search.toLowerCase())), [c.rows, search]);

  return <div className="mx-auto max-w-7xl space-y-6">
    <section className="flex flex-col gap-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7 lg:flex-row lg:items-center">
      <div className="flex min-w-0 flex-1 items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-teal-50 text-teal-600"><Icon size={24} /></span><div><p className="text-xs font-bold uppercase tracking-[.14em] text-teal-600">{c.eyebrow}</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">{c.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{c.description}</p></div></div>
      <button onClick={() => setModal(true)} className="flex items-center justify-center gap-2 rounded-xl bg-teal-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-teal-600/20 hover:bg-teal-700"><Plus size={18} />{c.action}</button>
    </section>
    <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{c.stats.map((s, i) => <article key={s.label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm font-medium text-slate-500">{s.label}</p><span className={`grid h-8 w-8 place-items-center rounded-lg ${i === 1 ? "bg-rose-50 text-rose-500" : "bg-teal-50 text-teal-600"}`}>{i === 0 ? <TrendingUp size={16} /> : i === 1 ? <CircleDollarSign size={16} /> : i === 2 ? <ClipboardCheck size={16} /> : <Sparkles size={16} />}</span></div><strong className="mt-3 block text-2xl font-bold text-slate-900">{s.value}</strong><span className="mt-1 block text-xs text-slate-400">{s.hint}</span></article>)}</section>
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
      <div className="flex flex-col gap-4 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between sm:px-6">
        <div className="flex gap-1 overflow-x-auto">{c.tabs.map(t => <button key={t} onClick={() => setTab(t)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-bold ${tab === t ? "bg-teal-50 text-teal-700" : "text-slate-500 hover:bg-slate-50"}`}>{t}</button>)}</div>
        <div className="flex items-center gap-2"><label className="relative flex-1 sm:w-64"><Search className="absolute left-3 top-2.5 text-slate-400" size={17} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar..." className="w-full rounded-xl border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none focus:border-teal-500" /></label><button aria-label="Filtros" className="rounded-xl border border-slate-200 p-2 text-slate-500 hover:bg-slate-50"><SlidersHorizontal size={18} /></button></div>
      </div>
      <div className="divide-y divide-slate-100">{rows.map(row => <button key={row.title} className="flex w-full items-center gap-4 px-4 py-4 text-left hover:bg-slate-50 sm:px-6"><span className="hidden h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-500 sm:grid"><Icon size={18} /></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-slate-800">{row.title}</strong><span className="mt-1 block truncate text-xs text-slate-500">{row.detail}</span></span><span className="hidden text-right text-xs text-slate-400 md:block">{row.meta}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${statusColor(row.status)}`}>{row.status}</span><ChevronRight className="text-slate-300" size={17} /></button>)}</div>
      <div className="flex items-center justify-between border-t border-slate-100 bg-slate-50/70 px-6 py-3 text-xs text-slate-400"><span>{rows.length} registros exibidos</span><button className="flex items-center gap-1 font-semibold text-teal-600">Ver todos<ArrowUpRight size={14} /></button></div>
    </section>
    {modal && <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/40 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-3xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-600">Protótipo interativo</p><h3 className="mt-1 text-xl font-bold text-slate-900">{c.action}</h3></div><button onClick={() => setModal(false)} className="rounded-xl p-2 text-slate-400 hover:bg-slate-100"><X size={20} /></button></div><div className="space-y-4 p-5"><label className="block text-sm font-semibold text-slate-700">Título<input autoFocus placeholder="Digite as informações principais" className="mt-1.5 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-teal-500" /></label><label className="block text-sm font-semibold text-slate-700">Observações<textarea rows={4} placeholder="Detalhes adicionais..." className="mt-1.5 w-full resize-none rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-teal-500" /></label><div className="rounded-xl bg-teal-50 p-3 text-xs leading-5 text-teal-700">Este formulário demonstra o fluxo e será conectado à base de dados na etapa funcional do módulo.</div></div><div className="flex justify-end gap-2 border-t border-slate-100 p-4"><button onClick={() => setModal(false)} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-500 hover:bg-slate-100">Cancelar</button><button onClick={() => setModal(false)} className="rounded-xl bg-teal-600 px-5 py-2.5 text-sm font-bold text-white hover:bg-teal-700">Salvar rascunho</button></div></div></div>}
  </div>;
}
